name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run workflow when pushing to the 'main' branch
  pull_request:
    branches:
      - main  # Run workflow for pull requests targeting 'main'

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust to your project's Node.js version

      # Install dependencies
      - name: Install Dependencies
        run: npm install


  cd:
    name: Continuous Deployment
    needs: ci 
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the project (if needed)
      - name: Build Project
        run: npm run build
